# Generated by Django 5.2 on 2025-04-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='basket',
        ),
        migrations.AddField(
            model_name='order',
            name='basket',
            field=models.ManyToManyField(to='api_crud.basket'),
        ),
    ]
